[build]
  command = "pnpm --filter ./frontend... run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  XATA_API_KEY = ""
  XATA_DATABASE_URL = ""

[functions]
  # Incluir el cliente de Xata en el bundle de la funci√≥n
  external_node_modules = ["@xata.io/client"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
