[build]
  base = "frontend"
  command = "pnpm run build"
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  XATA_API_KEY = ""
  XATA_DATABASE_URL = ""

[functions]
  external_node_modules = ["@xata.io/client"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
