[build]
  base = "frontend"
  command = "pnpm run build"
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  XATA_API_KEY = ""
  XATA_DATABASE_URL = ""

[functions]
  # Incluye el cliente de Xata en el bundle de la funci√≥n
  external_node_modules = ["@xata.io/client"]

# Si usas React / Vite SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
