[build]
  base = "frontend"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"
  functions = "./netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_USERCONFIG = ""
  NETLIFY_USE_PNPM = "true"
  XATA_API_KEY = ""
  XATA_DATABASE_URL = ""

[functions]
  external_node_modules = ["@xata.io/client"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200