[build]
  command = "pnpm --filter ./frontend... run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_USERCONFIG = ""
  NETLIFY_USE_PNPM = "true"
  XATA_API_KEY = ""
  XATA_DATABASE_URL = ""

[functions]
  external_node_modules = ["@xata.io/client"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
