[build]
  base = "frontend"
  command = "pnpm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  XATA_API_KEY = ""
  XATA_DATABASE_URL = ""

[functions]
  # Indica qué módulos externos deben incluirse en el bundle de las funciones
  external_node_modules = ["@xata.io/client"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
